import Country from 'model/Country';
import {search} from 'helpers/filterParser';
import ErrorResponse from 'helpers/errorResponse';
import errors from 'helpers/errors';

const searchTextFields = ['name', 'code2', 'code3', 'numericCode', 'turkishName', 'euMember'];
const adminFields = [];
const defaultProjection = ['shortId', 'name', 'code2', 'code3', 'numericCode', 'turkishName', 'euMember'];

const data = [
  {
    name: 'Afghanistan',
    code2: 'AF',
    code3: 'AFG',
    numericCode: 4,
    'Latitude (average)': 33,
    'Longitude (average)': 65,
    shortId: '',
  },
  {
    name: 'Albania',
    code2: 'AL',
    code3: 'ALB',
    numericCode: 8,
    'Latitude (average)': 41,
    'Longitude (average)': 20,
    shortId: '',
  },
  {
    name: 'Algeria',
    code2: 'DZ',
    code3: 'DZA',
    numericCode: 12,
    'Latitude (average)': 28,
    'Longitude (average)': 3,
    shortId: '',
  },
  {
    name: 'American Samoa',
    code2: 'AS',
    code3: 'ASM',
    numericCode: 16,
    'Latitude (average)': -14.3333,
    'Longitude (average)': -170,
    shortId: '',
  },
  {
    name: 'Andorra',
    code2: 'AD',
    code3: 'AND',
    numericCode: 20,
    'Latitude (average)': 42.5,
    'Longitude (average)': 1.6,
    shortId: '',
  },
  {
    name: 'Angola',
    code2: 'AO',
    code3: 'AGO',
    numericCode: 24,
    'Latitude (average)': -12.5,
    'Longitude (average)': 18.5,
    shortId: '',
  },
  {
    name: 'Anguilla',
    code2: 'AI',
    code3: 'AIA',
    numericCode: 660,
    'Latitude (average)': 18.25,
    'Longitude (average)': -63.1667,
    shortId: '',
  },
  {
    name: 'Antarctica',
    code2: 'AQ',
    code3: 'ATA',
    numericCode: 10,
    'Latitude (average)': -90,
    'Longitude (average)': 0,
    shortId: '',
  },
  {
    name: 'Antigua and Barbuda',
    code2: 'AG',
    code3: 'ATG',
    numericCode: 28,
    'Latitude (average)': 17.05,
    'Longitude (average)': -61.8,
    shortId: '',
  },
  {
    name: 'Argentina',
    code2: 'AR',
    code3: 'ARG',
    numericCode: 32,
    'Latitude (average)': -34,
    'Longitude (average)': -64,
    shortId: '',
  },
  {
    name: 'Armenia',
    code2: 'AM',
    code3: 'ARM',
    numericCode: 51,
    'Latitude (average)': 40,
    'Longitude (average)': 45,
    shortId: '',
  },
  {
    name: 'Aruba',
    code2: 'AW',
    code3: 'ABW',
    numericCode: 533,
    'Latitude (average)': 12.5,
    'Longitude (average)': -69.9667,
    shortId: '',
  },
  {
    name: 'Australia',
    code2: 'AU',
    code3: 'AUS',
    numericCode: 36,
    'Latitude (average)': -27,
    'Longitude (average)': 133,
    shortId: '',
  },
  {
    name: 'Austria',
    turkishName: 'Avusturya',
    code2: 'AT',
    code3: 'AUT',
    numericCode: 40,
    'Latitude (average)': 47.3333,
    'Longitude (average)': 13.3333,
    shortId: '',
    euMember: true,
  },
  {
    name: 'Azerbaijan',
    code2: 'AZ',
    code3: 'AZE',
    numericCode: 31,
    'Latitude (average)': 40.5,
    'Longitude (average)': 47.5,
    shortId: '',
  },
  {
    name: 'Bahamas',
    code2: 'BS',
    code3: 'BHS',
    numericCode: 44,
    'Latitude (average)': 24.25,
    'Longitude (average)': -76,
    shortId: '',
  },
  {
    name: 'Bahrain',
    code2: 'BH',
    code3: 'BHR',
    numericCode: 48,
    'Latitude (average)': 26,
    'Longitude (average)': 50.55,
    shortId: '',
  },
  {
    name: 'Bangladesh',
    code2: 'BD',
    code3: 'BGD',
    numericCode: 50,
    'Latitude (average)': 24,
    'Longitude (average)': 90,
    shortId: '',
  },
  {
    name: 'Barbados',
    code2: 'BB',
    code3: 'BRB',
    numericCode: 52,
    'Latitude (average)': 13.1667,
    'Longitude (average)': -59.5333,
    shortId: '',
  },
  {
    name: 'Belarus',
    code2: 'BY',
    code3: 'BLR',
    numericCode: 112,
    'Latitude (average)': 53,
    'Longitude (average)': 28,
    shortId: '',
  },
  {
    name: 'Belgium',
    turkishName: 'Belçika',
    code2: 'BE',
    code3: 'BEL',
    numericCode: 56,
    'Latitude (average)': 50.8333,
    'Longitude (average)': 4,
    shortId: '',
    euMember: true,
  },
  {
    name: 'Belize',
    code2: 'BZ',
    code3: 'BLZ',
    numericCode: 84,
    'Latitude (average)': 17.25,
    'Longitude (average)': -88.75,
    shortId: '',
  },
  {
    name: 'Benin',
    code2: 'BJ',
    code3: 'BEN',
    numericCode: 204,
    'Latitude (average)': 9.5,
    'Longitude (average)': 2.25,
    shortId: '',
  },
  {
    name: 'Bermuda',
    code2: 'BM',
    code3: 'BMU',
    numericCode: 60,
    'Latitude (average)': 32.3333,
    'Longitude (average)': -64.75,
    shortId: '',
  },
  {
    name: 'Bhutan',
    code2: 'BT',
    code3: 'BTN',
    numericCode: 64,
    'Latitude (average)': 27.5,
    'Longitude (average)': 90.5,
    shortId: '',
  },
  {
    name: 'Bolivia, Plurinational State of',
    code2: 'BO',
    code3: 'BOL',
    numericCode: 68,
    'Latitude (average)': -17,
    'Longitude (average)': -65,
    shortId: '',
  },
  {
    name: 'Bolivia',
    code2: 'BO',
    code3: 'BOL',
    numericCode: 68,
    'Latitude (average)': -17,
    'Longitude (average)': -65,
    shortId: '',
  },
  {
    name: 'Bosnia and Herzegovina',
    code2: 'BA',
    code3: 'BIH',
    numericCode: 70,
    'Latitude (average)': 44,
    'Longitude (average)': 18,
    shortId: '',
  },
  {
    name: 'Botswana',
    code2: 'BW',
    code3: 'BWA',
    numericCode: 72,
    'Latitude (average)': -22,
    'Longitude (average)': 24,
    shortId: '',
  },
  {
    name: 'Bouvet Island',
    code2: 'BV',
    code3: 'BVT',
    numericCode: 74,
    'Latitude (average)': -54.4333,
    'Longitude (average)': 3.4,
    shortId: '',
  },
  {
    name: 'Brazil',
    code2: 'BR',
    code3: 'BRA',
    numericCode: 76,
    'Latitude (average)': -10,
    'Longitude (average)': -55,
    shortId: '',
  },
  {
    name: 'British Indian Ocean Territory',
    code2: 'IO',
    code3: 'IOT',
    numericCode: 86,
    'Latitude (average)': -6,
    'Longitude (average)': 71.5,
    shortId: '',
  },
  {
    name: 'Brunei Darussalam',
    code2: 'BN',
    code3: 'BRN',
    numericCode: 96,
    'Latitude (average)': 4.5,
    'Longitude (average)': 114.6667,
    shortId: '',
  },
  {
    name: 'Brunei',
    code2: 'BN',
    code3: 'BRN',
    numericCode: 96,
    'Latitude (average)': 4.5,
    'Longitude (average)': 114.6667,
    shortId: '',
  },
  {
    name: 'Bulgaria',
    turkishName: 'Bulgaristan',
    code2: 'BG',
    code3: 'BGR',
    numericCode: 100,
    'Latitude (average)': 43,
    'Longitude (average)': 25,
    shortId: '',
    euMember: true,
  },
  {
    name: 'Burkina Faso',
    code2: 'BF',
    code3: 'BFA',
    numericCode: 854,
    'Latitude (average)': 13,
    'Longitude (average)': -2,
    shortId: '',
  },
  {
    name: 'Burundi',
    code2: 'BI',
    code3: 'BDI',
    numericCode: 108,
    'Latitude (average)': -3.5,
    'Longitude (average)': 30,
    shortId: '',
  },
  {
    name: 'Cambodia',
    code2: 'KH',
    code3: 'KHM',
    numericCode: 116,
    'Latitude (average)': 13,
    'Longitude (average)': 105,
    shortId: '',
  },
  {
    name: 'Cameroon',
    code2: 'CM',
    code3: 'CMR',
    numericCode: 120,
    'Latitude (average)': 6,
    'Longitude (average)': 12,
    shortId: '',
  },
  {
    name: 'Canada',
    code2: 'CA',
    code3: 'CAN',
    numericCode: 124,
    'Latitude (average)': 60,
    'Longitude (average)': -95,
    shortId: '',
  },
  {
    name: 'Cape Verde',
    code2: 'CV',
    code3: 'CPV',
    numericCode: 132,
    'Latitude (average)': 16,
    'Longitude (average)': -24,
    shortId: '',
  },
  {
    name: 'Cayman Islands',
    code2: 'KY',
    code3: 'CYM',
    numericCode: 136,
    'Latitude (average)': 19.5,
    'Longitude (average)': -80.5,
    shortId: '',
  },
  {
    name: 'Central African Republic',
    code2: 'CF',
    code3: 'CAF',
    numericCode: 140,
    'Latitude (average)': 7,
    'Longitude (average)': 21,
    shortId: '',
  },
  {
    name: 'Chad',
    code2: 'TD',
    code3: 'TCD',
    numericCode: 148,
    'Latitude (average)': 15,
    'Longitude (average)': 19,
    shortId: '',
  },
  {
    name: 'Chile',
    code2: 'CL',
    code3: 'CHL',
    numericCode: 152,
    'Latitude (average)': -30,
    'Longitude (average)': -71,
    shortId: '',
  },
  {
    name: 'China',
    code2: 'CN',
    code3: 'CHN',
    numericCode: 156,
    'Latitude (average)': 35,
    'Longitude (average)': 105,
    shortId: '',
  },
  {
    name: 'Christmas Island',
    code2: 'CX',
    code3: 'CXR',
    numericCode: 162,
    'Latitude (average)': -10.5,
    'Longitude (average)': 105.6667,
    shortId: '',
  },
  {
    name: 'Cocos (Keeling) Islands',
    code2: 'CC',
    code3: 'CCK',
    numericCode: 166,
    'Latitude (average)': -12.5,
    'Longitude (average)': 96.8333,
    shortId: '',
  },
  {
    name: 'Colombia',
    code2: 'CO',
    code3: 'COL',
    numericCode: 170,
    'Latitude (average)': 4,
    'Longitude (average)': -72,
    shortId: '',
  },
  {
    name: 'Comoros',
    code2: 'KM',
    code3: 'COM',
    numericCode: 174,
    'Latitude (average)': -12.1667,
    'Longitude (average)': 44.25,
    shortId: '',
  },
  {
    name: 'Congo',
    code2: 'CG',
    code3: 'COG',
    numericCode: 178,
    'Latitude (average)': -1,
    'Longitude (average)': 15,
    shortId: '',
  },
  {
    name: 'Congo, the Democratic Republic of the',
    code2: 'CD',
    code3: 'COD',
    numericCode: 180,
    'Latitude (average)': 0,
    'Longitude (average)': 25,
    shortId: '',
  },
  {
    name: 'Cook Islands',
    code2: 'CK',
    code3: 'COK',
    numericCode: 184,
    'Latitude (average)': -21.2333,
    'Longitude (average)': -159.7667,
    shortId: '',
  },
  {
    name: 'Costa Rica',
    code2: 'CR',
    code3: 'CRI',
    numericCode: 188,
    'Latitude (average)': 10,
    'Longitude (average)': -84,
    shortId: '',
  },
  {
    name: "Côte d'Ivoire",
    code2: 'CI',
    code3: 'CIV',
    numericCode: 384,
    'Latitude (average)': 8,
    'Longitude (average)': -5,
    shortId: '',
  },
  {
    name: 'Ivory Coast',
    code2: 'CI',
    code3: 'CIV',
    numericCode: 384,
    'Latitude (average)': 8,
    'Longitude (average)': -5,
    shortId: '',
  },
  {
    name: 'Croatia',
    turkishName: 'Hırvatistan',
    code2: 'HR',
    code3: 'HRV',
    numericCode: 191,
    'Latitude (average)': 45.1667,
    'Longitude (average)': 15.5,
    shortId: '',
    euMember: true,
  },
  {
    name: 'Cuba',
    code2: 'CU',
    code3: 'CUB',
    numericCode: 192,
    'Latitude (average)': 21.5,
    'Longitude (average)': -80,
    shortId: '',
  },
  {
    name: 'Cyprus',
    code2: 'CY',
    code3: 'CYP',
    numericCode: 196,
    'Latitude (average)': 35,
    'Longitude (average)': 33,
    shortId: '',
  },
  {
    name: 'Czech Republic',
    turkishName: 'Çekya',
    code2: 'CZ',
    code3: 'CZE',
    numericCode: 203,
    'Latitude (average)': 49.75,
    'Longitude (average)': 15.5,
    shortId: '',
    euMember: true,
  },
  {
    name: 'Denmark',
    turkishName: 'Danimarka',
    code2: 'DK',
    code3: 'DNK',
    numericCode: 208,
    'Latitude (average)': 56,
    'Longitude (average)': 10,
    shortId: '',
    euMember: true,
  },
  {
    name: 'Djibouti',
    code2: 'DJ',
    code3: 'DJI',
    numericCode: 262,
    'Latitude (average)': 11.5,
    'Longitude (average)': 43,
    shortId: '',
  },
  {
    name: 'Dominica',
    code2: 'DM',
    code3: 'DMA',
    numericCode: 212,
    'Latitude (average)': 15.4167,
    'Longitude (average)': -61.3333,
    shortId: '',
  },
  {
    name: 'Dominican Republic',
    code2: 'DO',
    code3: 'DOM',
    numericCode: 214,
    'Latitude (average)': 19,
    'Longitude (average)': -70.6667,
    shortId: '',
  },
  {
    name: 'Ecuador',
    code2: 'EC',
    code3: 'ECU',
    numericCode: 218,
    'Latitude (average)': -2,
    'Longitude (average)': -77.5,
    shortId: '',
  },
  {
    name: 'Egypt',
    code2: 'EG',
    code3: 'EGY',
    numericCode: 818,
    'Latitude (average)': 27,
    'Longitude (average)': 30,
    shortId: '',
  },
  {
    name: 'El Salvador',
    code2: 'SV',
    code3: 'SLV',
    numericCode: 222,
    'Latitude (average)': 13.8333,
    'Longitude (average)': -88.9167,
    shortId: '',
  },
  {
    name: 'Equatorial Guinea',
    code2: 'GQ',
    code3: 'GNQ',
    numericCode: 226,
    'Latitude (average)': 2,
    'Longitude (average)': 10,
    shortId: '',
  },
  {
    name: 'Eritrea',
    code2: 'ER',
    code3: 'ERI',
    numericCode: 232,
    'Latitude (average)': 15,
    'Longitude (average)': 39,
    shortId: '',
  },
  {
    name: 'Estonia',
    turkishName: 'Estonya',
    code2: 'EE',
    code3: 'EST',
    numericCode: 233,
    'Latitude (average)': 59,
    'Longitude (average)': 26,
    shortId: '',
    euMember: true,
  },
  {
    name: 'Ethiopia',
    code2: 'ET',
    code3: 'ETH',
    numericCode: 231,
    'Latitude (average)': 8,
    'Longitude (average)': 38,
    shortId: '',
  },
  {
    name: 'Falkland Islands (Malvinas)',
    code2: 'FK',
    code3: 'FLK',
    numericCode: 238,
    'Latitude (average)': -51.75,
    'Longitude (average)': -59,
    shortId: '',
  },
  {
    name: 'Faroe Islands',
    code2: 'FO',
    code3: 'FRO',
    numericCode: 234,
    'Latitude (average)': 62,
    'Longitude (average)': -7,
    shortId: '',
  },
  {
    name: 'Fiji',
    code2: 'FJ',
    code3: 'FJI',
    numericCode: 242,
    'Latitude (average)': -18,
    'Longitude (average)': 175,
    shortId: '',
  },
  {
    name: 'Finland',
    turkishName: 'Finlandiya',
    code2: 'FI',
    code3: 'FIN',
    numericCode: 246,
    'Latitude (average)': 64,
    'Longitude (average)': 26,
    shortId: '',
    euMember: true,
  },
  {
    name: 'France',
    turkishName: 'Fransa',
    code2: 'FR',
    code3: 'FRA',
    numericCode: 250,
    'Latitude (average)': 46,
    'Longitude (average)': 2,
    shortId: '',
    euMember: true,
  },
  {
    name: 'French Guiana',
    code2: 'GF',
    code3: 'GUF',
    numericCode: 254,
    'Latitude (average)': 4,
    'Longitude (average)': -53,
    shortId: '',
  },
  {
    name: 'French Polynesia',
    code2: 'PF',
    code3: 'PYF',
    numericCode: 258,
    'Latitude (average)': -15,
    'Longitude (average)': -140,
    shortId: '',
  },
  {
    name: 'French Southern Territories',
    code2: 'TF',
    code3: 'ATF',
    numericCode: 260,
    'Latitude (average)': -43,
    'Longitude (average)': 67,
    shortId: '',
  },
  {
    name: 'Gabon',
    code2: 'GA',
    code3: 'GAB',
    numericCode: 266,
    'Latitude (average)': -1,
    'Longitude (average)': 11.75,
    shortId: '',
  },
  {
    name: 'Gambia',
    code2: 'GM',
    code3: 'GMB',
    numericCode: 270,
    'Latitude (average)': 13.4667,
    'Longitude (average)': -16.5667,
    shortId: '',
  },
  {
    name: 'Georgia',
    code2: 'GE',
    code3: 'GEO',
    numericCode: 268,
    'Latitude (average)': 42,
    'Longitude (average)': 43.5,
    shortId: '',
  },
  {
    name: 'Germany',
    turkishName: 'Almanya',
    code2: 'DE',
    code3: 'DEU',
    numericCode: 276,
    'Latitude (average)': 51,
    'Longitude (average)': 9,
    shortId: '',
    euMember: true,
  },
  {
    name: 'Ghana',
    code2: 'GH',
    code3: 'GHA',
    numericCode: 288,
    'Latitude (average)': 8,
    'Longitude (average)': -2,
    shortId: '',
  },
  {
    name: 'Gibraltar',
    code2: 'GI',
    code3: 'GIB',
    numericCode: 292,
    'Latitude (average)': 36.1833,
    'Longitude (average)': -5.3667,
    shortId: '',
  },
  {
    name: 'Greece',
    turkishName: 'Yunanistan',
    code2: 'GR',
    code3: 'GRC',
    numericCode: 300,
    'Latitude (average)': 39,
    'Longitude (average)': 22,
    shortId: '',
    euMember: true,
  },
  {
    name: 'Greenland',
    code2: 'GL',
    code3: 'GRL',
    numericCode: 304,
    'Latitude (average)': 72,
    'Longitude (average)': -40,
    shortId: '',
  },
  {
    name: 'Grenada',
    code2: 'GD',
    code3: 'GRD',
    numericCode: 308,
    'Latitude (average)': 12.1167,
    'Longitude (average)': -61.6667,
    shortId: '',
  },
  {
    name: 'Guadeloupe',
    code2: 'GP',
    code3: 'GLP',
    numericCode: 312,
    'Latitude (average)': 16.25,
    'Longitude (average)': -61.5833,
    shortId: '',
  },
  {
    name: 'Guam',
    code2: 'GU',
    code3: 'GUM',
    numericCode: 316,
    'Latitude (average)': 13.4667,
    'Longitude (average)': 144.7833,
    shortId: '',
  },
  {
    name: 'Guatemala',
    code2: 'GT',
    code3: 'GTM',
    numericCode: 320,
    'Latitude (average)': 15.5,
    'Longitude (average)': -90.25,
    shortId: '',
  },
  {
    name: 'Guernsey',
    code2: 'GG',
    code3: 'GGY',
    numericCode: 831,
    'Latitude (average)': 49.5,
    'Longitude (average)': -2.56,
    shortId: '',
  },
  {
    name: 'Guinea',
    code2: 'GN',
    code3: 'GIN',
    numericCode: 324,
    'Latitude (average)': 11,
    'Longitude (average)': -10,
    shortId: '',
  },
  {
    name: 'Guinea-Bissau',
    code2: 'GW',
    code3: 'GNB',
    numericCode: 624,
    'Latitude (average)': 12,
    'Longitude (average)': -15,
    shortId: '',
  },
  {
    name: 'Guyana',
    code2: 'GY',
    code3: 'GUY',
    numericCode: 328,
    'Latitude (average)': 5,
    'Longitude (average)': -59,
    shortId: '',
  },
  {
    name: 'Haiti',
    code2: 'HT',
    code3: 'HTI',
    numericCode: 332,
    'Latitude (average)': 19,
    'Longitude (average)': -72.4167,
    shortId: '',
  },
  {
    name: 'Heard Island and McDonald Islands',
    code2: 'HM',
    code3: 'HMD',
    numericCode: 334,
    'Latitude (average)': -53.1,
    'Longitude (average)': 72.5167,
    shortId: '',
  },
  {
    name: 'Holy See (Vatican City State)',
    code2: 'VA',
    code3: 'VAT',
    numericCode: 336,
    'Latitude (average)': 41.9,
    'Longitude (average)': 12.45,
    shortId: '',
  },
  {
    name: 'Honduras',
    code2: 'HN',
    code3: 'HND',
    numericCode: 340,
    'Latitude (average)': 15,
    'Longitude (average)': -86.5,
    shortId: '',
  },
  {
    name: 'Hong Kong',
    code2: 'HK',
    code3: 'HKG',
    numericCode: 344,
    'Latitude (average)': 22.25,
    'Longitude (average)': 114.1667,
    shortId: '',
  },
  {
    name: 'Hungary',
    turkishName: 'Macaristan',
    code2: 'HU',
    code3: 'HUN',
    numericCode: 348,
    'Latitude (average)': 47,
    'Longitude (average)': 20,
    shortId: '',
    euMember: true,
  },
  {
    name: 'Iceland',
    code2: 'IS',
    code3: 'ISL',
    numericCode: 352,
    'Latitude (average)': 65,
    'Longitude (average)': -18,
    shortId: '',
  },
  {
    name: 'India',
    code2: 'IN',
    code3: 'IND',
    numericCode: 356,
    'Latitude (average)': 20,
    'Longitude (average)': 77,
    shortId: '',
  },
  {
    name: 'Indonesia',
    code2: 'ID',
    code3: 'IDN',
    numericCode: 360,
    'Latitude (average)': -5,
    'Longitude (average)': 120,
    shortId: '',
  },
  {
    name: 'Iran, Islamic Republic of',
    code2: 'IR',
    code3: 'IRN',
    numericCode: 364,
    'Latitude (average)': 32,
    'Longitude (average)': 53,
    shortId: '',
  },
  {
    name: 'Iraq',
    code2: 'IQ',
    code3: 'IRQ',
    numericCode: 368,
    'Latitude (average)': 33,
    'Longitude (average)': 44,
    shortId: '',
  },
  {
    name: 'Ireland',
    turkishName: 'İrlanda',
    code2: 'IE',
    code3: 'IRL',
    numericCode: 372,
    'Latitude (average)': 53,
    'Longitude (average)': -8,
    shortId: '',
    euMember: true,
  },
  {
    name: 'Isle of Man',
    code2: 'IM',
    code3: 'IMN',
    numericCode: 833,
    'Latitude (average)': 54.23,
    'Longitude (average)': -4.55,
    shortId: '',
  },
  {
    name: 'Israel',
    code2: 'IL',
    code3: 'ISR',
    numericCode: 376,
    'Latitude (average)': 31.5,
    'Longitude (average)': 34.75,
    shortId: '',
  },
  {
    name: 'Italy',
    turkishName: 'İtalya',
    code2: 'IT',
    code3: 'ITA',
    numericCode: 380,
    'Latitude (average)': 42.8333,
    'Longitude (average)': 12.8333,
    shortId: '',
    euMember: true,
  },
  {
    name: 'Jamaica',
    code2: 'JM',
    code3: 'JAM',
    numericCode: 388,
    'Latitude (average)': 18.25,
    'Longitude (average)': -77.5,
    shortId: '',
  },
  {
    name: 'Japan',
    code2: 'JP',
    code3: 'JPN',
    numericCode: 392,
    'Latitude (average)': 36,
    'Longitude (average)': 138,
    shortId: '',
  },
  {
    name: 'Jersey',
    code2: 'JE',
    code3: 'JEY',
    numericCode: 832,
    'Latitude (average)': 49.21,
    'Longitude (average)': -2.13,
    shortId: '',
  },
  {
    name: 'Jordan',
    code2: 'JO',
    code3: 'JOR',
    numericCode: 400,
    'Latitude (average)': 31,
    'Longitude (average)': 36,
    shortId: '',
  },
  {
    name: 'Kazakhstan',
    code2: 'KZ',
    code3: 'KAZ',
    numericCode: 398,
    'Latitude (average)': 48,
    'Longitude (average)': 68,
    shortId: '',
  },
  {
    name: 'Kenya',
    code2: 'KE',
    code3: 'KEN',
    numericCode: 404,
    'Latitude (average)': 1,
    'Longitude (average)': 38,
    shortId: '',
  },
  {
    name: 'Kiribati',
    code2: 'KI',
    code3: 'KIR',
    numericCode: 296,
    'Latitude (average)': 1.4167,
    'Longitude (average)': 173,
    shortId: '',
  },
  {
    name: "Korea, Democratic People's Republic of",
    code2: 'KP',
    code3: 'PRK',
    numericCode: 408,
    'Latitude (average)': 40,
    'Longitude (average)': 127,
    shortId: '',
  },
  {
    name: 'Korea, Republic of',
    code2: 'KR',
    code3: 'KOR',
    numericCode: 410,
    'Latitude (average)': 37,
    'Longitude (average)': 127.5,
    shortId: '',
  },
  {
    name: 'South Korea',
    code2: 'KR',
    code3: 'KOR',
    numericCode: 410,
    'Latitude (average)': 37,
    'Longitude (average)': 127.5,
    shortId: '',
  },
  {
    name: 'Kuwait',
    code2: 'KW',
    code3: 'KWT',
    numericCode: 414,
    'Latitude (average)': 29.3375,
    'Longitude (average)': 47.6581,
    shortId: '',
  },
  {
    name: 'Kyrgyzstan',
    code2: 'KG',
    code3: 'KGZ',
    numericCode: 417,
    'Latitude (average)': 41,
    'Longitude (average)': 75,
    shortId: '',
  },
  {
    name: "Lao People's Democratic Republic",
    code2: 'LA',
    code3: 'LAO',
    numericCode: 418,
    'Latitude (average)': 18,
    'Longitude (average)': 105,
    shortId: '',
  },
  {
    name: 'Latvia',
    turkishName: 'Letonya',
    code2: 'LV',
    code3: 'LVA',
    numericCode: 428,
    'Latitude (average)': 57,
    'Longitude (average)': 25,
    shortId: '',
    euMember: true,
  },
  {
    name: 'Lebanon',
    code2: 'LB',
    code3: 'LBN',
    numericCode: 422,
    'Latitude (average)': 33.8333,
    'Longitude (average)': 35.8333,
    shortId: '',
  },
  {
    name: 'Lesotho',
    code2: 'LS',
    code3: 'LSO',
    numericCode: 426,
    'Latitude (average)': -29.5,
    'Longitude (average)': 28.5,
    shortId: '',
  },
  {
    name: 'Liberia',
    code2: 'LR',
    code3: 'LBR',
    numericCode: 430,
    'Latitude (average)': 6.5,
    'Longitude (average)': -9.5,
    shortId: '',
  },
  {
    name: 'Libyan Arab Jamahiriya',
    code2: 'LY',
    code3: 'LBY',
    numericCode: 434,
    'Latitude (average)': 25,
    'Longitude (average)': 17,
    shortId: '',
  },
  {
    name: 'Libya',
    code2: 'LY',
    code3: 'LBY',
    numericCode: 434,
    'Latitude (average)': 25,
    'Longitude (average)': 17,
    shortId: '',
  },
  {
    name: 'Liechtenstein',
    code2: 'LI',
    code3: 'LIE',
    numericCode: 438,
    'Latitude (average)': 47.1667,
    'Longitude (average)': 9.5333,
    shortId: '',
  },
  {
    name: 'Lithuania',
    turkishName: 'Litvanya',
    code2: 'LT',
    code3: 'LTU',
    numericCode: 440,
    'Latitude (average)': 56,
    'Longitude (average)': 24,
    shortId: '',
    euMember: true,
  },
  {
    name: 'Luxembourg',
    turkishName: 'Lüksemburg',
    code2: 'LU',
    code3: 'LUX',
    numericCode: 442,
    'Latitude (average)': 49.75,
    'Longitude (average)': 6.1667,
    shortId: '',
    euMember: true,
  },
  {
    name: 'Macao',
    code2: 'MO',
    code3: 'MAC',
    numericCode: 446,
    'Latitude (average)': 22.1667,
    'Longitude (average)': 113.55,
    shortId: '',
  },
  {
    name: 'Macedonia, the former Yugoslav Republic of',
    code2: 'MK',
    code3: 'MKD',
    numericCode: 807,
    'Latitude (average)': 41.8333,
    'Longitude (average)': 22,
    shortId: '',
  },
  {
    name: 'Madagascar',
    code2: 'MG',
    code3: 'MDG',
    numericCode: 450,
    'Latitude (average)': -20,
    'Longitude (average)': 47,
    shortId: '',
  },
  {
    name: 'Malawi',
    code2: 'MW',
    code3: 'MWI',
    numericCode: 454,
    'Latitude (average)': -13.5,
    'Longitude (average)': 34,
    shortId: '',
  },
  {
    name: 'Malaysia',
    code2: 'MY',
    code3: 'MYS',
    numericCode: 458,
    'Latitude (average)': 2.5,
    'Longitude (average)': 112.5,
    shortId: '',
  },
  {
    name: 'Maldives',
    code2: 'MV',
    code3: 'MDV',
    numericCode: 462,
    'Latitude (average)': 3.25,
    'Longitude (average)': 73,
    shortId: '',
  },
  {
    name: 'Mali',
    code2: 'ML',
    code3: 'MLI',
    numericCode: 466,
    'Latitude (average)': 17,
    'Longitude (average)': -4,
    shortId: '',
  },
  {
    name: 'Malta',
    turkishName: 'Malta',
    code2: 'MT',
    code3: 'MLT',
    numericCode: 470,
    'Latitude (average)': 35.8333,
    'Longitude (average)': 14.5833,
    shortId: '',
    euMember: true,
  },
  {
    name: 'Marshall Islands',
    code2: 'MH',
    code3: 'MHL',
    numericCode: 584,
    'Latitude (average)': 9,
    'Longitude (average)': 168,
    shortId: '',
  },
  {
    name: 'Martinique',
    code2: 'MQ',
    code3: 'MTQ',
    numericCode: 474,
    'Latitude (average)': 14.6667,
    'Longitude (average)': -61,
    shortId: '',
  },
  {
    name: 'Mauritania',
    code2: 'MR',
    code3: 'MRT',
    numericCode: 478,
    'Latitude (average)': 20,
    'Longitude (average)': -12,
    shortId: '',
  },
  {
    name: 'Mauritius',
    code2: 'MU',
    code3: 'MUS',
    numericCode: 480,
    'Latitude (average)': -20.2833,
    'Longitude (average)': 57.55,
    shortId: '',
  },
  {
    name: 'Mayotte',
    code2: 'YT',
    code3: 'MYT',
    numericCode: 175,
    'Latitude (average)': -12.8333,
    'Longitude (average)': 45.1667,
    shortId: '',
  },
  {
    name: 'Mexico',
    code2: 'MX',
    code3: 'MEX',
    numericCode: 484,
    'Latitude (average)': 23,
    'Longitude (average)': -102,
    shortId: '',
  },
  {
    name: 'Micronesia, Federated States of',
    code2: 'FM',
    code3: 'FSM',
    numericCode: 583,
    'Latitude (average)': 6.9167,
    'Longitude (average)': 158.25,
    shortId: '',
  },
  {
    name: 'Moldova, Republic of',
    code2: 'MD',
    code3: 'MDA',
    numericCode: 498,
    'Latitude (average)': 47,
    'Longitude (average)': 29,
    shortId: '',
  },
  {
    name: 'Monaco',
    code2: 'MC',
    code3: 'MCO',
    numericCode: 492,
    'Latitude (average)': 43.7333,
    'Longitude (average)': 7.4,
    shortId: '',
  },
  {
    name: 'Mongolia',
    code2: 'MN',
    code3: 'MNG',
    numericCode: 496,
    'Latitude (average)': 46,
    'Longitude (average)': 105,
    shortId: '',
  },
  {
    name: 'Montenegro',
    code2: 'ME',
    code3: 'MNE',
    numericCode: 499,
    'Latitude (average)': 42,
    'Longitude (average)': 19,
    shortId: '',
  },
  {
    name: 'Montserrat',
    code2: 'MS',
    code3: 'MSR',
    numericCode: 500,
    'Latitude (average)': 16.75,
    'Longitude (average)': -62.2,
    shortId: '',
  },
  {
    name: 'Morocco',
    code2: 'MA',
    code3: 'MAR',
    numericCode: 504,
    'Latitude (average)': 32,
    'Longitude (average)': -5,
    shortId: '',
  },
  {
    name: 'Mozambique',
    code2: 'MZ',
    code3: 'MOZ',
    numericCode: 508,
    'Latitude (average)': -18.25,
    'Longitude (average)': 35,
    shortId: '',
  },
  {
    name: 'Myanmar',
    code2: 'MM',
    code3: 'MMR',
    numericCode: 104,
    'Latitude (average)': 22,
    'Longitude (average)': 98,
    shortId: '',
  },
  {
    name: 'Burma',
    code2: 'MM',
    code3: 'MMR',
    numericCode: 104,
    'Latitude (average)': 22,
    'Longitude (average)': 98,
    shortId: '',
  },
  {
    name: 'Namibia',
    code2: 'NA',
    code3: 'NAM',
    numericCode: 516,
    'Latitude (average)': -22,
    'Longitude (average)': 17,
    shortId: '',
  },
  {
    name: 'Nauru',
    code2: 'NR',
    code3: 'NRU',
    numericCode: 520,
    'Latitude (average)': -0.5333,
    'Longitude (average)': 166.9167,
    shortId: '',
  },
  {
    name: 'Nepal',
    code2: 'NP',
    code3: 'NPL',
    numericCode: 524,
    'Latitude (average)': 28,
    'Longitude (average)': 84,
    shortId: '',
  },
  {
    name: 'Netherlands',
    turkishName: 'Hollanda',
    code2: 'NL',
    code3: 'NLD',
    numericCode: 528,
    'Latitude (average)': 52.5,
    'Longitude (average)': 5.75,
    shortId: '',
    euMember: true,
  },
  {
    name: 'Netherlands Antilles',
    code2: 'AN',
    code3: 'ANT',
    numericCode: 530,
    'Latitude (average)': 12.25,
    'Longitude (average)': -68.75,
    shortId: '',
  },
  {
    name: 'New Caledonia',
    code2: 'NC',
    code3: 'NCL',
    numericCode: 540,
    'Latitude (average)': -21.5,
    'Longitude (average)': 165.5,
    shortId: '',
  },
  {
    name: 'New Zealand',
    code2: 'NZ',
    code3: 'NZL',
    numericCode: 554,
    'Latitude (average)': -41,
    'Longitude (average)': 174,
    shortId: '',
  },
  {
    name: 'Nicaragua',
    code2: 'NI',
    code3: 'NIC',
    numericCode: 558,
    'Latitude (average)': 13,
    'Longitude (average)': -85,
    shortId: '',
  },
  {
    name: 'Niger',
    code2: 'NE',
    code3: 'NER',
    numericCode: 562,
    'Latitude (average)': 16,
    'Longitude (average)': 8,
    shortId: '',
  },
  {
    name: 'Nigeria',
    code2: 'NG',
    code3: 'NGA',
    numericCode: 566,
    'Latitude (average)': 10,
    'Longitude (average)': 8,
    shortId: '',
  },
  {
    name: 'Niue',
    code2: 'NU',
    code3: 'NIU',
    numericCode: 570,
    'Latitude (average)': -19.0333,
    'Longitude (average)': -169.8667,
    shortId: '',
  },
  {
    name: 'Norfolk Island',
    code2: 'NF',
    code3: 'NFK',
    numericCode: 574,
    'Latitude (average)': -29.0333,
    'Longitude (average)': 167.95,
    shortId: '',
  },
  {
    name: 'Northern Mariana Islands',
    code2: 'MP',
    code3: 'MNP',
    numericCode: 580,
    'Latitude (average)': 15.2,
    'Longitude (average)': 145.75,
    shortId: '',
  },
  {
    name: 'Norway',
    code2: 'NO',
    code3: 'NOR',
    numericCode: 578,
    'Latitude (average)': 62,
    'Longitude (average)': 10,
    shortId: '',
  },
  {
    name: 'Oman',
    code2: 'OM',
    code3: 'OMN',
    numericCode: 512,
    'Latitude (average)': 21,
    'Longitude (average)': 57,
    shortId: '',
  },
  {
    name: 'Pakistan',
    code2: 'PK',
    code3: 'PAK',
    numericCode: 586,
    'Latitude (average)': 30,
    'Longitude (average)': 70,
    shortId: '',
  },
  {
    name: 'Palau',
    code2: 'PW',
    code3: 'PLW',
    numericCode: 585,
    'Latitude (average)': 7.5,
    'Longitude (average)': 134.5,
    shortId: '',
  },
  {
    name: 'Palestinian Territory, Occupied',
    code2: 'PS',
    code3: 'PSE',
    numericCode: 275,
    'Latitude (average)': 32,
    'Longitude (average)': 35.25,
    shortId: '',
  },
  {
    name: 'Panama',
    code2: 'PA',
    code3: 'PAN',
    numericCode: 591,
    'Latitude (average)': 9,
    'Longitude (average)': -80,
    shortId: '',
  },
  {
    name: 'Papua New Guinea',
    code2: 'PG',
    code3: 'PNG',
    numericCode: 598,
    'Latitude (average)': -6,
    'Longitude (average)': 147,
    shortId: '',
  },
  {
    name: 'Paraguay',
    code2: 'PY',
    code3: 'PRY',
    numericCode: 600,
    'Latitude (average)': -23,
    'Longitude (average)': -58,
    shortId: '',
  },
  {
    name: 'Peru',
    code2: 'PE',
    code3: 'PER',
    numericCode: 604,
    'Latitude (average)': -10,
    'Longitude (average)': -76,
    shortId: '',
  },
  {
    name: 'Philippines',
    code2: 'PH',
    code3: 'PHL',
    numericCode: 608,
    'Latitude (average)': 13,
    'Longitude (average)': 122,
    shortId: '',
  },
  {
    name: 'Pitcairn',
    code2: 'PN',
    code3: 'PCN',
    numericCode: 612,
    'Latitude (average)': -24.7,
    'Longitude (average)': -127.4,
    shortId: '',
  },
  {
    name: 'Poland',
    turkishName: 'Polonya',
    code2: 'PL',
    code3: 'POL',
    numericCode: 616,
    'Latitude (average)': 52,
    'Longitude (average)': 20,
    shortId: '',
    euMember: true,
  },
  {
    name: 'Portugal',
    turkishName: 'Portekiz',
    code2: 'PT',
    code3: 'PRT',
    numericCode: 620,
    'Latitude (average)': 39.5,
    'Longitude (average)': -8,
    shortId: '',
    euMember: true,
  },
  {
    name: 'Puerto Rico',
    code2: 'PR',
    code3: 'PRI',
    numericCode: 630,
    'Latitude (average)': 18.25,
    'Longitude (average)': -66.5,
    shortId: '',
  },
  {
    name: 'Qatar',
    code2: 'QA',
    code3: 'QAT',
    numericCode: 634,
    'Latitude (average)': 25.5,
    'Longitude (average)': 51.25,
    shortId: '',
  },
  {
    name: 'Réunion',
    code2: 'RE',
    code3: 'REU',
    numericCode: 638,
    'Latitude (average)': -21.1,
    'Longitude (average)': 55.6,
    shortId: '',
  },
  {
    name: 'Romania',
    turkishName: 'Romanya',
    code2: 'RO',
    code3: 'ROU',
    numericCode: 642,
    'Latitude (average)': 46,
    'Longitude (average)': 25,
    shortId: '',
    euMember: true,
  },
  {
    name: 'Russian Federation',
    code2: 'RU',
    code3: 'RUS',
    numericCode: 643,
    'Latitude (average)': 60,
    'Longitude (average)': 100,
    shortId: '',
  },
  {
    name: 'Russia',
    code2: 'RU',
    code3: 'RUS',
    numericCode: 643,
    'Latitude (average)': 60,
    'Longitude (average)': 100,
    shortId: '',
  },
  {
    name: 'Rwanda',
    code2: 'RW',
    code3: 'RWA',
    numericCode: 646,
    'Latitude (average)': -2,
    'Longitude (average)': 30,
    shortId: '',
  },
  {
    name: 'Saint Helena, Ascension and Tristan da Cunha',
    code2: 'SH',
    code3: 'SHN',
    numericCode: 654,
    'Latitude (average)': -15.9333,
    'Longitude (average)': -5.7,
    shortId: '',
  },
  {
    name: 'Saint Kitts and Nevis',
    code2: 'KN',
    code3: 'KNA',
    numericCode: 659,
    'Latitude (average)': 17.3333,
    'Longitude (average)': -62.75,
    shortId: '',
  },
  {
    name: 'Saint Lucia',
    code2: 'LC',
    code3: 'LCA',
    numericCode: 662,
    'Latitude (average)': 13.8833,
    'Longitude (average)': -61.1333,
    shortId: '',
  },
  {
    name: 'Saint Pierre and Miquelon',
    code2: 'PM',
    code3: 'SPM',
    numericCode: 666,
    'Latitude (average)': 46.8333,
    'Longitude (average)': -56.3333,
    shortId: '',
  },
  {
    name: 'Saint Vincent and the Grenadines',
    code2: 'VC',
    code3: 'VCT',
    numericCode: 670,
    'Latitude (average)': 13.25,
    'Longitude (average)': -61.2,
    shortId: '',
  },
  {
    name: 'Saint Vincent & the Grenadines',
    code2: 'VC',
    code3: 'VCT',
    numericCode: 670,
    'Latitude (average)': 13.25,
    'Longitude (average)': -61.2,
    shortId: '',
  },
  {
    name: 'St. Vincent and the Grenadines',
    code2: 'VC',
    code3: 'VCT',
    numericCode: 670,
    'Latitude (average)': 13.25,
    'Longitude (average)': -61.2,
    shortId: '',
  },
  {
    name: 'Samoa',
    code2: 'WS',
    code3: 'WSM',
    numericCode: 882,
    'Latitude (average)': -13.5833,
    'Longitude (average)': -172.3333,
    shortId: '',
  },
  {
    name: 'San Marino',
    code2: 'SM',
    code3: 'SMR',
    numericCode: 674,
    'Latitude (average)': 43.7667,
    'Longitude (average)': 12.4167,
    shortId: '',
  },
  {
    name: 'Sao Tome and Principe',
    code2: 'ST',
    code3: 'STP',
    numericCode: 678,
    'Latitude (average)': 1,
    'Longitude (average)': 7,
    shortId: '',
  },
  {
    name: 'Saudi Arabia',
    code2: 'SA',
    code3: 'SAU',
    numericCode: 682,
    'Latitude (average)': 25,
    'Longitude (average)': 45,
    shortId: '',
  },
  {
    name: 'Senegal',
    code2: 'SN',
    code3: 'SEN',
    numericCode: 686,
    'Latitude (average)': 14,
    'Longitude (average)': -14,
    shortId: '',
  },
  {
    name: 'Serbia',
    code2: 'RS',
    code3: 'SRB',
    numericCode: 688,
    'Latitude (average)': 44,
    'Longitude (average)': 21,
    shortId: '',
  },
  {
    name: 'Seychelles',
    code2: 'SC',
    code3: 'SYC',
    numericCode: 690,
    'Latitude (average)': -4.5833,
    'Longitude (average)': 55.6667,
    shortId: '',
  },
  {
    name: 'Sierra Leone',
    code2: 'SL',
    code3: 'SLE',
    numericCode: 694,
    'Latitude (average)': 8.5,
    'Longitude (average)': -11.5,
    shortId: '',
  },
  {
    name: 'Singapore',
    code2: 'SG',
    code3: 'SGP',
    numericCode: 702,
    'Latitude (average)': 1.3667,
    'Longitude (average)': 103.8,
    shortId: '',
  },
  {
    name: 'Slovakia',
    turkishName: 'Slovakya',
    code2: 'SK',
    code3: 'SVK',
    numericCode: 703,
    'Latitude (average)': 48.6667,
    'Longitude (average)': 19.5,
    shortId: '',
    euMember: true,
  },
  {
    name: 'Slovenia',
    turkishName: 'Slovenya',
    code2: 'SI',
    code3: 'SVN',
    numericCode: 705,
    'Latitude (average)': 46,
    'Longitude (average)': 15,
    shortId: '',
    euMember: true,
  },
  {
    name: 'Solomon Islands',
    code2: 'SB',
    code3: 'SLB',
    numericCode: 90,
    'Latitude (average)': -8,
    'Longitude (average)': 159,
    shortId: '',
  },
  {
    name: 'Somalia',
    code2: 'SO',
    code3: 'SOM',
    numericCode: 706,
    'Latitude (average)': 10,
    'Longitude (average)': 49,
    shortId: '',
  },
  {
    name: 'South Africa',
    code2: 'ZA',
    code3: 'ZAF',
    numericCode: 710,
    'Latitude (average)': -29,
    'Longitude (average)': 24,
    shortId: '',
  },
  {
    name: 'South Georgia and the South Sandwich Islands',
    code2: 'GS',
    code3: 'SGS',
    numericCode: 239,
    'Latitude (average)': -54.5,
    'Longitude (average)': -37,
    shortId: '',
  },
  {
    name: 'South Sudan',
    code2: 'SS',
    code3: 'SSD',
    numericCode: 728,
    'Latitude (average)': 8,
    'Longitude (average)': 30,
    shortId: '',
  },
  {
    name: 'Spain',
    turkishName: 'İspanya',
    code2: 'ES',
    code3: 'ESP',
    numericCode: 724,
    'Latitude (average)': 40,
    'Longitude (average)': -4,
    shortId: '',
    euMember: true,
  },
  {
    name: 'Sri Lanka',
    code2: 'LK',
    code3: 'LKA',
    numericCode: 144,
    'Latitude (average)': 7,
    'Longitude (average)': 81,
    shortId: '',
  },
  {
    name: 'Sudan',
    code2: 'SD',
    code3: 'SDN',
    numericCode: 736,
    'Latitude (average)': 15,
    'Longitude (average)': 30,
    shortId: '',
  },
  {
    name: 'Suriname',
    code2: 'SR',
    code3: 'SUR',
    numericCode: 740,
    'Latitude (average)': 4,
    'Longitude (average)': -56,
    shortId: '',
  },
  {
    name: 'Svalbard and Jan Mayen',
    code2: 'SJ',
    code3: 'SJM',
    numericCode: 744,
    'Latitude (average)': 78,
    'Longitude (average)': 20,
    shortId: '',
  },
  {
    name: 'Swaziland',
    code2: 'SZ',
    code3: 'SWZ',
    numericCode: 748,
    'Latitude (average)': -26.5,
    'Longitude (average)': 31.5,
    shortId: '',
  },
  {
    name: 'Sweden',
    turkishName: 'İsveç',
    code2: 'SE',
    code3: 'SWE',
    numericCode: 752,
    'Latitude (average)': 62,
    'Longitude (average)': 15,
    shortId: '',
    euMember: true,
  },
  {
    name: 'Switzerland',
    code2: 'CH',
    code3: 'CHE',
    numericCode: 756,
    'Latitude (average)': 47,
    'Longitude (average)': 8,
    shortId: '',
  },
  {
    name: 'Syrian Arab Republic',
    code2: 'SY',
    code3: 'SYR',
    numericCode: 760,
    'Latitude (average)': 35,
    'Longitude (average)': 38,
    shortId: '',
  },
  {
    name: 'Taiwan, Province of China',
    code2: 'TW',
    code3: 'TWN',
    numericCode: 158,
    'Latitude (average)': 23.5,
    'Longitude (average)': 121,
    shortId: '',
  },
  {
    name: 'Taiwan',
    code2: 'TW',
    code3: 'TWN',
    numericCode: 158,
    'Latitude (average)': 23.5,
    'Longitude (average)': 121,
    shortId: '',
  },
  {
    name: 'Tajikistan',
    code2: 'TJ',
    code3: 'TJK',
    numericCode: 762,
    'Latitude (average)': 39,
    'Longitude (average)': 71,
    shortId: '',
  },
  {
    name: 'Tanzania, United Republic of',
    code2: 'TZ',
    code3: 'TZA',
    numericCode: 834,
    'Latitude (average)': -6,
    'Longitude (average)': 35,
    shortId: '',
  },
  {
    name: 'Thailand',
    code2: 'TH',
    code3: 'THA',
    numericCode: 764,
    'Latitude (average)': 15,
    'Longitude (average)': 100,
    shortId: '',
  },
  {
    name: 'Timor-Leste',
    code2: 'TL',
    code3: 'TLS',
    numericCode: 626,
    'Latitude (average)': -8.55,
    'Longitude (average)': 125.5167,
    shortId: '',
  },
  {
    name: 'Togo',
    code2: 'TG',
    code3: 'TGO',
    numericCode: 768,
    'Latitude (average)': 8,
    'Longitude (average)': 1.1667,
    shortId: '',
  },
  {
    name: 'Tokelau',
    code2: 'TK',
    code3: 'TKL',
    numericCode: 772,
    'Latitude (average)': -9,
    'Longitude (average)': -172,
    shortId: '',
  },
  {
    name: 'Tonga',
    code2: 'TO',
    code3: 'TON',
    numericCode: 776,
    'Latitude (average)': -20,
    'Longitude (average)': -175,
    shortId: '',
  },
  {
    name: 'Trinidad and Tobago',
    code2: 'TT',
    code3: 'TTO',
    numericCode: 780,
    'Latitude (average)': 11,
    'Longitude (average)': -61,
    shortId: '',
  },
  {
    name: 'Tunisia',
    code2: 'TN',
    code3: 'TUN',
    numericCode: 788,
    'Latitude (average)': 34,
    'Longitude (average)': 9,
    shortId: '',
  },
  {
    name: 'Turkey',
    code2: 'TR',
    code3: 'TUR',
    numericCode: 792,
    'Latitude (average)': 39,
    'Longitude (average)': 35,
    shortId: '',
  },
  {
    name: 'Turkmenistan',
    code2: 'TM',
    code3: 'TKM',
    numericCode: 795,
    'Latitude (average)': 40,
    'Longitude (average)': 60,
    shortId: '',
  },
  {
    name: 'Turks and Caicos Islands',
    code2: 'TC',
    code3: 'TCA',
    numericCode: 796,
    'Latitude (average)': 21.75,
    'Longitude (average)': -71.5833,
    shortId: '',
  },
  {
    name: 'Tuvalu',
    code2: 'TV',
    code3: 'TUV',
    numericCode: 798,
    'Latitude (average)': -8,
    'Longitude (average)': 178,
    shortId: '',
  },
  {
    name: 'Uganda',
    code2: 'UG',
    code3: 'UGA',
    numericCode: 800,
    'Latitude (average)': 1,
    'Longitude (average)': 32,
    shortId: '',
  },
  {
    name: 'Ukraine',
    code2: 'UA',
    code3: 'UKR',
    numericCode: 804,
    'Latitude (average)': 49,
    'Longitude (average)': 32,
    shortId: '',
  },
  {
    name: 'United Arab Emirates',
    code2: 'AE',
    code3: 'ARE',
    numericCode: 784,
    'Latitude (average)': 24,
    'Longitude (average)': 54,
    shortId: '',
  },
  {
    name: 'United Kingdom',
    code2: 'GB',
    code3: 'GBR',
    numericCode: 826,
    'Latitude (average)': 54,
    'Longitude (average)': -2,
    shortId: '',
  },
  {
    name: 'United States',
    code2: 'US',
    code3: 'USA',
    numericCode: 840,
    'Latitude (average)': 38,
    'Longitude (average)': -97,
    shortId: '',
  },
  {
    name: 'United States Minor Outlying Islands',
    code2: 'UM',
    code3: 'UMI',
    numericCode: 581,
    'Latitude (average)': 19.2833,
    'Longitude (average)': 166.6,
    shortId: '',
  },
  {
    name: 'Uruguay',
    code2: 'UY',
    code3: 'URY',
    numericCode: 858,
    'Latitude (average)': -33,
    'Longitude (average)': -56,
    shortId: '',
  },
  {
    name: 'Uzbekistan',
    code2: 'UZ',
    code3: 'UZB',
    numericCode: 860,
    'Latitude (average)': 41,
    'Longitude (average)': 64,
    shortId: '',
  },
  {
    name: 'Vanuatu',
    code2: 'VU',
    code3: 'VUT',
    numericCode: 548,
    'Latitude (average)': -16,
    'Longitude (average)': 167,
    shortId: '',
  },
  {
    name: 'Venezuela, Bolivarian Republic of',
    code2: 'VE',
    code3: 'VEN',
    numericCode: 862,
    'Latitude (average)': 8,
    'Longitude (average)': -66,
    shortId: '',
  },
  {
    name: 'Venezuela',
    code2: 'VE',
    code3: 'VEN',
    numericCode: 862,
    'Latitude (average)': 8,
    'Longitude (average)': -66,
    shortId: '',
  },
  {
    name: 'Viet Nam',
    code2: 'VN',
    code3: 'VNM',
    numericCode: 704,
    'Latitude (average)': 16,
    'Longitude (average)': 106,
    shortId: '',
  },
  {
    name: 'Vietnam',
    code2: 'VN',
    code3: 'VNM',
    numericCode: 704,
    'Latitude (average)': 16,
    'Longitude (average)': 106,
    shortId: '',
  },
  {
    name: 'Virgin Islands, British',
    code2: 'VG',
    code3: 'VGB',
    numericCode: 92,
    'Latitude (average)': 18.5,
    'Longitude (average)': -64.5,
    shortId: '',
  },
  {
    name: 'Virgin Islands, U.S.',
    code2: 'VI',
    code3: 'VIR',
    numericCode: 850,
    'Latitude (average)': 18.3333,
    'Longitude (average)': -64.8333,
    shortId: '',
  },
  {
    name: 'Wallis and Futuna',
    code2: 'WF',
    code3: 'WLF',
    numericCode: 876,
    'Latitude (average)': -13.3,
    'Longitude (average)': -176.2,
    shortId: '',
  },
  {
    name: 'Western Sahara',
    code2: 'EH',
    code3: 'ESH',
    numericCode: 732,
    'Latitude (average)': 24.5,
    'Longitude (average)': -13,
    shortId: '',
  },
  {
    name: 'Yemen',
    code2: 'YE',
    code3: 'YEM',
    numericCode: 887,
    'Latitude (average)': 15,
    'Longitude (average)': 48,
    shortId: '',
  },
  {
    name: 'Zambia',
    code2: 'ZM',
    code3: 'ZMB',
    numericCode: 894,
    'Latitude (average)': -15,
    'Longitude (average)': 30,
    shortId: '',
  },
  {
    name: 'Zimbabwe',
    code2: 'ZW',
    code3: 'ZWE',
    numericCode: 716,
    'Latitude (average)': -20,
    'Longitude (average)': 30,
    shortId: '',
  },
];

export const getCountry = async (req, res, next) => {
  const {id} = req.params;
  const country = await Country.findById({_id: id}).lean();
  res.send(country);
};

export const searchCountry = async (req, res) => {
  const filter = req.body.filter || {fields: [{condition: 'equal', value: true, dataField: 'euMember'}]};

  res.send(await search(null, Country, searchTextFields, filter, defaultProjection, adminFields));
};

export const initCountry = async (req, res) => {
  // let x = 0;
  // for (x = 0; x < data.length; x++) {
  //   const newCountry = new Country({
  //     name: data[x].name,
  //     code2: data[x].code2,
  //     code3: data[x].code3,
  //     numericCode: data[x].numericCode,
  //     turkishName: data[x]?.turkishName || '',
  //     euMember: data[x]?.euMember || false,
  //   });
  //   let result = await newCountry.save();
  //   console.log('result', result);
  // }
  res.send('OK');
};
